### ISSUE TITLE
ViT

### ISSUE THREAD

**Issue by pcc-99** [fgirbal/segment-select-correct#1]
For the results in your paper, do you use ViT-L/14@336px or ViT-B32 as the CLIP visual encoder?

**Comment by fgirbal** [comment]
For the zero-shot selection mechanism (Stage 2), we use ViT-L/14@336px. We use ViT-B32 for the dataset class projection in Stage 1 and the ablation of the zero-shot selection mechanism in Section 4.3.

**Comment by qiulesun** [comment]
@fgirbal 
Hi, to reproduce results of S+S (ours) under ZS setting in Table 1, the step of **4. Testing unsupervised masks** in README reports such results (e.g., oIoU 33.31, mIoU 36.95 on RefCOCO val in Table 1) ?

**Comment by fgirbal** [comment]
Yes, @qiulesun, setting up as per the README ([Getting Started](https://github.com/fgirbal/segment-select-correct?tab=readme-ov-file#getting-started) and [Running Stages 1, 2 and 3](https://github.com/fgirbal/segment-select-correct?tab=readme-ov-file#running-stages-1-2-and-3)), and then following [2. Segment: Generating all the masks](https://github.com/fgirbal/segment-select-correct?tab=readme-ov-file#2-segment-generating-all-the-masks) and [4. Testing unsupervised masks](https://github.com/fgirbal/segment-select-correct?tab=readme-ov-file#4-testing-unsupervised-masks) should give you the results of S+S in Table 1.
