### ISSUE TITLE
Error: NameError: name '_C' is not defined ; ----- failed to detect anything ----

### ISSUE THREAD

**Issue by Valeria281856** [fgirbal/segment-select-correct#3]
When I run the command "python scripts/create_all_masks_dataset.py -n example -d refcocog --split-by google --dataset-root /data/lv/expr/TRIS/data/refer --most-likely-noun --project --context-projections -f", it always occurs that :
NameError: name '_C' is not defined

----- failed to detect anything ----
0%| | 3/44822 [00:08<35:11:50, 2.83s/it]

What happened and how can I solve it?

**Comment by fgirbal** [comment]
Hi @xiao-11, I'm not entirely sure where the error is just based on your description. Could you post the full output log with the trace?

**Comment by Valeria281856** [comment]
Thank you for receiving, I have solved it. It's a problem from the package installation of GroundingDINO. 

Now I want to know why the "use mask_choice to mask" step occurred in both "segment stage" and "select staget" in  test_unsupervised_masks_dataset.py ???

**Comment by fgirbal** [comment]
`mask_choice` is an argument associated with the selection stage that is passed in `test_unsupervised_masks_dataset.py` to enable the ablations provided in the paper at that stage (`reverse_blur` is the choice used by our method). 

`args.stage` in that same script only serves to identify where to read the masks from, either the output of a `segment` stage where there are multiple masks per object, or out of the output of a `select` stage using the script `create_zero_shot_masks_dataset.py` ([see the README info on this](https://github.com/fgirbal/segment-select-correct/tree/main?tab=readme-ov-file#4-testing-unsupervised-masks)). This is useful for ablations.

I'll consider the original issue closed, but feel free to open a new one if there are other issues with the code.
